### ISSUE TITLE
Missing system log files in ubuntu 14.04

### ISSUE THREAD

**Issue by nlm** [scaleway/image-ubuntu#10]
After fresh install, some logfiles are not created, like:
- syslog
- auth.log
- mail.log
- ...

The problem comes from the fact that the `/var/log` directory group is `utmpter` instead of `syslog`, thus preventing rsyslogd from creating new files in this directory (rsyslogd runs as `syslog:syslog`)

`apt-get install --reinstall install rsyslog` changes the group to `syslog`, which confirms that the `/var/log` directory mode is meant to be `775` and owner `root:syslog`

**Comment by moul** [comment]
Related with #2

**Comment by DomenicoCasillo** [comment]
I can confirm the issue.
Moreover it prevents apps like Fail2Ban to work as it expect to find those log file.

**Comment by suside** [comment]
I've got this issue with instance created August 2019.
When you hit `No file(s) found for glob /var/log/auth.log` error with `fail2ban` just set:
`backend = systemd`
in 
`/etc/fail2ban/jail.conf`
