### ISSUE TITLE
Ubuntu 17.04/Zesty is broken on ARM64.

### ISSUE THREAD

**Issue by Nurrl** [scaleway/image-ubuntu#106]
Hi, 
I noticed that Ubuntu Zesty on ARM64 is not working since the sources.list entries are not relevant anymore. So if anybody installs it, the *apt* CLI won't work.

Reference: http://ports.ubuntu.com/dists/
There is no 'zesty', 'zesty-backports' or 'zesty-security'.

**Comment by halmartin** [comment]
As @t0b1nux said, normal Ubuntu (non-LTS) releases are only supported for 9 months:
https://en.wikipedia.org/wiki/Ubuntu_(operating_system)#Releases

17.04 is EoL as of January 2018.

We will be releasing 18.04 LTS for ARM64 soon. Please use an LTS release such as 16.04 or 18.04.
