### ISSUE TITLE
Add Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ivkos** [scaleway/image-ubuntu#108]

**Comment by halmartin** [comment]
@ivkos 18.04 images will be released next week :thumbsup:

**Comment by hatarist** [comment]
@halmartin You mean, this week it'll be possible to set up a fresh server with the 18.04 via the cloud.scaleway.com? That's awesome, thanks a lot! Is there any closer ETA? (sorry for disturbing)

**Comment by halmartin** [comment]
@hatarist that's the plan! Unfortunately we've hit a bug booting on C2 instances which we'd like to clear up before releasing the image.

**Comment by hatarist** [comment]
Ok, thanks a lot! I tried to upgrade the C2L instance myself manually via the `do-release-upgrade` and that didn't end good for me, either :)

**Comment by estan** [comment]
It would be good if there was some official information on whether a `do-release-upgrade` on your own is safe/doable. I'm guessing it is not, judging by what people who have attempted it have been writing.

We started out with a GitLab image which was 16.04-based, but would really like to move it to 18.04. What are our options currently?
