### ISSUE TITLE
Ubuntu Xenial x64 Doesn't Start SSH

### ISSUE THREAD

**Issue by danhunsaker** [scaleway/image-ubuntu#111]
- https://cloud.scaleway.com/#/zones/par1/images/5ee7c699-d26a-477c-b0b3-6232c789ae3e
- https://cloud.scaleway.com/#/zones/ams1/images/f60fe15d-711c-4564-9aef-dadd5e97c394

I've created servers using the above-linked images, and cannot access them via SSH. The connection simply times out every time. This, of course, makes it very difficult to do anything useful with the server, so I'm certain this isn't the expected behavior.

Further details on request!

**Comment by danhunsaker** [comment]
highlighting @halmartin and @superseed at @sieben's suggestion.

**Comment by danhunsaker** [comment]
A hard reboot (since I couldn't do a soft one) results in SSH coming up correctly, so it's only an issue on first boot, apparently.

**Comment by danhunsaker** [comment]
Everything else works just fine, near as I can tell. At least, after the hard reset, everything we use at Nanobox works as expected. :slightly_smiling_face:

**Comment by halmartin** [comment]
@danhunsaker thanks for pointing this out. It's probably an issue with the order that unit files are executed.

Tomorrow is a holiday in France, so I'll have a look Wednesday.

**Comment by halmartin** [comment]
@danhunsaker I tried to reproduce this using a VC1S and the Ubuntu Xenial image and I'm not experiencing any issues logging in with SSH on first boot. I also checked the systemd unit file for `scw-generate-ssh-keys` and as far as I can tell, there's no way sshd should be starting before the SSH keys are installed.

Could you please provide more details:
  - Are you creating the instance via the API or the console?
  - What instance type are you creating? C1, C2, ARM64, VC1, X64?
  - Are there any messages about services failing to start in the console boot log?

If you can also open a ticket and send us the output of `scw inspect` for an instance you're having these issues with. Thanks!

**Comment by danhunsaker** [comment]
Sorry for the delay getting back to you. Lots going on.

Point by point:
- API (I'm implementing the Libcloud driver for Scaleway, in part for use at Nanobox)
- VC1S, probably local since I'm not setting a script, but just relying on the image to set things up
- Haven't seen the boot log for first boot; may need some hand holding to track that down.

I can grab that info from the API in just a moment. :slightly_smiling_face:

**Comment by danhunsaker** [comment]
Hmm. Seems to have vanished in Paris. Amsterdam is having trouble even starting the START1-XS I ordered there, but I suspect that might be an availability issue.

**Comment by halmartin** [comment]
@danhunsaker well, sorry to hear that you can't reproduce the issue, but I'm glad to hear it seems to be resolved.

Feel free to re-open this if you experience it again!
