### ISSUE TITLE
Ubuntu Xenial. Why do you clean up the interfaces every reboot?

### ISSUE THREAD

**Issue by jackivanov** [scaleway/image-ubuntu#115]
Hello,

I configured additional interfaces inside the /etc/network/interfaces.d/ directory and after reboot they disappeared. What is the reason of this? Could you just leave all the files as they are, please?

How to reproduce:
- touch /etc/network/interfaces.d/test
- reboot
- /etc/network/interfaces.d/test is missing

**Comment by halmartin** [comment]
@jackivanov Please create your file in `/etc/network/interfaces.d/` with the extension `.user.cfg`

Following your example, this would be `test.user.cfg` and it will not be deleted on reboot.
