### ISSUE TITLE
Suggest adding command-not-found as default package

### ISSUE THREAD

**Issue by ivorget** [scaleway/image-ubuntu#120]
Even as an experienced linux user I find the`command-not-found`package very useful and it is especially helpful for novice users so I suggest adding it as a default package. It gives more helpful responses for unrecognized commands in the shell, for example:
```
> do-release-upgrade
Command 'do-release-upgrade' not found, but can be installed with:

apt install ubuntu-release-upgrader-core
```

**Comment by halmartin** [comment]
Hi @ivorget 

`command-not-found` is already installed in the Bionic image:
```
root@scw-ce1187:~# dpkg -l | grep command-not-found
ii  command-not-found                     18.04.4                           all          Suggest installation of packages in interactive bash sessions
ii  command-not-found-data                18.04.4                           amd64        Set of data files for command-not-found.
ii  python3-commandnotfound               18.04.4                           all          Python 3 bindings for command-not-found.
```

It is included in the [ubuntu-standard](https://packages.ubuntu.com/bionic/ubuntu-standard) package group as a recommended package.

This package group is not installed in Xenial. I will add `command-not-found` to Xenial so the behaviour is consistent between Bionic and Xenial. See https://github.com/scaleway/image-ubuntu/pull/121
