### ISSUE TITLE
550 Access denied - Invalid HELO name

### ISSUE THREAD

**Issue by GeGeek** [scaleway/image-ubuntu#31]
Hi,

i was getting this error when i tried to send an email to fully qualifed domain name, and not with free email services like hotmail, gmail etc..

So i fixed that by editing the file main.cf in /etc/postfix/

I changed the value for "myhostname = ", the default value was something like B84665785255..

Could you fix it in the next release please ?

Thanks !

**Comment by moul** [comment]
Hi @GeGeek

The Ubuntu image we provide does not contain postfix

can you give us more context ?

cc @edouardb @bchatelard

**Comment by GeGeek** [comment]
Hi,

yes of course, i have installed Gitlab, and no email were sent, so i asked why to support, and they told me that:

>I have been looking into your issue, we are going to fix this very soon.
>https://github.com/scaleway-community/scaleway-gitlab/issues/6
>
>In the mean time, you should be able to send mail by running:
>'dpkg-reconfigure postfix'

I installed postfix and i noticed that no mail log file was installed in my server, so the support told me that:

>The default configuration of the postfix server is to put logs in /var/log/syslog.
>
>Unfortunately, the latest build of your image has his syslog broken, you need to run 'chown >root:syslog /var/log' to fix it.
>https://github.com/scaleway/image-ubuntu/pull/22

After that emails was working, but not correctly, and in log files i was able to see "invalid hello name...
So i found the solution and the support told me to report this issue here !

:smiley:

**Comment by moul** [comment]
Continuing discussion here: https://github.com/scaleway-community/scaleway-gitlab/issues/7
