### ISSUE TITLE
Does this replace the armbuild/ubuntu image?

### ISSUE THREAD

**Issue by janeczku** [scaleway/image-ubuntu#36]
Since the armbuild/ubuntu image has disappeared from docker hub, are we supposed to use this as base image for creating new docker images for running in containers on C1 servers?

**Comment by moul** [comment]
Hi @janeczku there are 2 different kind of images here:

- https://hub.docker.com/r/armbuild/ubuntu/ built with https://github.com/armbuild/docker-brew-ubuntu-debootstrap which is the equivalent of the official ubuntu image https://github.com/tianon/docker-brew-ubuntu-debootstrap but for ARM architecture
- https://hub.docker.com/r/scaleway/ubuntu/ built with this repo which is the image used to build other images on Scaleway, it contains a standard Ubuntu + needed scripts to boot on C1 servers

---

* If you want to create Docker containers for ARMHF you can use both of these images, but I suggest you to use the smallest one: `armbuild/ubuntu`
* If you want to build a server image, you need to inherit from one of these images https://hub.docker.com/u/scaleway/

**Comment by janeczku** [comment]
Hi @moul thanks for the great info! I was confused about the 'debootstrap' in the repository name not realising that this is in fact the arm equivalent of the official Ubuntu image.

**Comment by moul** [comment]
You're welcome :)
