### ISSUE TITLE
resolv.conf keeps on getting overwritten

### ISSUE THREAD

**Issue by staticfloat** [scaleway/image-ubuntu#47]
I can't resolve `build.julialang.org` when using the default DNS servers, and although things work when I change the DNS servers to `8.8.8.8` and `8.8.4.4`, these changes keep on getting reverted by some program.

**Comment by moul** [comment]
Hi @staticfloat,

We are managing the `/etc/resolv.conf` file using the initrd (see https://github.com/scaleway/initrd/blob/master/Linux/tree-common/init#L207).
This scripts first checks if the `resolv.conf` file is empty, if it is, the file is not overwritten, if the file is empty, then the script appends the default nameserver.

In your case, if you already have a manually crafted `/etc/resolv.conf` file, then the initrd won't do anything.

---

So I think that your `/etc/resolv.conf` file keeps being overwritten by the default ubuntu's DHCP hook.

Which Ubuntu version are you using ? precise, trusty, utopic, vivid, xenial, other ?
I should help you configure your Ubuntu version to disable this behavior

Else you can try to fix it by yourself using one of these methods: http://www.cyberciti.biz/faq/dhclient-etcresolvconf-hooks/

**Comment by staticfloat** [comment]
I'm using `trusty`, and following the instructions linked in the above page, I created a `/etc/dhcp/dhclient-enter-hooks.d/nodnsupdate` file, that looks like this;

```
$ cat nodnsupdate
#!/bin/sh
make_resolv_conf(){
        :
}
```

This seems to be working, thanks.

**Comment by fvigotti** [comment]
to me still not working,
ubuntu 16.04 and /etc/dhcp/dhclient-enter-hooks.d/nodnsupdate in place with +x
but something still appending 

> domain cloud.online.net
> nameserver 10.1.94.8

to my resolv.conf file at every boot ..

**Comment by fvigotti** [comment]
the workaround for me is : "chattr +i /etc/resolv.conf"
but this is very inelegant... I would like to know what is changing /etc/resolv.conf and how to avoid that.. anyone has suggestions ? 
thanks,

**Comment by gonzalo-radio** [comment]
Another solution is modify the `/etc/dhcp/dhclient.conf` configuration file and remove these elements on the request:

```
domain-name
domain-name-servers
domain-search
dhcp6.name-servers
dhcp6.domain-search
```

Hope this is helpful for anyone.
