### ISSUE TITLE
Ubuntu 16.04 Xenial on C1: timeout on serial at startup

### ISSUE THREAD

**Issue by skimpax** [scaleway/image-ubuntu#66]
Created a fresh C1 server with Ubuntu 16.04 Xenial image.
On boot, timeout error is displayed when setting up ttyS0:
"Timed out waiting for dev-ttyS0.device" and "Dependency failed for Serial Getty on ttyS0" messages are displayed on console"

Installing udev (apt-get install udev) fixes the error.
Same issue as https://github.com/scaleway/image-debian/issues/61

Please add udev in Xenial Dockerfile

**Comment by moul** [comment]
Hi @skimpax 

Thanks for your feedback, it will be released at the beginning of the next week
