### ISSUE TITLE
linux-image-extra missing (Docker degradation)

### ISSUE THREAD

**Issue by kapolos** [scaleway/image-ubuntu#70]
The `linux-image-extra-?` package is not available for the current Xenial kernel on C2. This is a huge problem with Docker, as without it `aufs` cannot be used and it falls back to `device mapper`.

To reproduce, simply install Docker from the official [instructions](https://docs.docker.com/engine/installation/linux/ubuntulinux/) and run `docker info`

````
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
````

It's not a "never happens" warning, I've lost data with device mapper before :(

Note that `aufs` will get installed but the kernel support for it is on the missing package, so it will not be enabled.

**Comment by QuentinPerez** [comment]
Hi @kapolos,

Are you using the docker  bootscript ? You can find the instructions [here](https://github.com/scaleway/image-ubuntu/issues/68#issuecomment-225250604)

**Comment by kapolos** [comment]
Hi @QuentinPerez ,

No, I wasn't aware of that, thnak you. I spinned a new instance to test but not sure if any of the available bootscripts is valid for this:
![](http://i.imgur.com/zOOlNJh.png)

The Xenial repos have the "extra" package for 4.4 kernels and these are all 4.5.x.

**Comment by QuentinPerez** [comment]
You can use the bootscript 4.5.4 - docker, then reboot your instance and reinstall docker. It's should work.

**Comment by kapolos** [comment]
It worked indeed!

````
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
````

Thank you @QuentinPerez ! :beers:

**Comment by QuentinPerez** [comment]
Nice, Now I am going to have a nice sleep 😁

**Comment by kapolos** [comment]
:bouquet: :sleeping: :zzz: :+1: :bouquet:
