### ISSUE TITLE
Ubuntu 16.04 kernel and Docker Swarm Mode

### ISSUE THREAD

**Issue by jesuscript** [scaleway/image-ubuntu#78]
Hi,

I have been having problems with connectivity between different nodes in a Docker Swarm Mode cluster and it has been pointed out to me that the problem lies in my kernel missing IPVS modules needed for load balancing (IPVS_NFCT and IPVS_RR). See this thread for more details: https://github.com/docker/docker/issues/28168

The kernel currently used in 16.04 images is 4.5.7-std-3. Is there another kernel that you could recommend which would have the required kernel configs and also work well on scaleway servers? Alternatively, I'm happy to follow any other recommendation for setting up a Docker Swarm cluster. Thanks!

**Comment by QuentinPerez** [comment]
Hi @jesuscript,

You must use the docker bootscript e.g `4.8.3 docker`.
To use a different bootscript you can follow these [instructions](https://www.scaleway.com/docs/bootscript-and-how-to-use-it/)

**Comment by jesuscript** [comment]
cool, thanks! oddly, the instructions only talk about how to change a server's bootscript, but not how to select one before it's created. Do you know if it's even possible?

**Comment by QuentinPerez** [comment]
Yes you can, but only with the [CLI] (github.com/scaleway/scaleway-cli) `scw run --bootscript=docker xenial`

**Comment by jesuscript** [comment]
ahha! brilliant, thanks so much! Just one more thing: where is the best place to find the list of available bootscripts?

**Comment by QuentinPerez** [comment]
Currently you can only list the public bootscripts.

```console
scw images -f type=bootscript
REPOSITORY                  TAG                 IMAGE ID            CREATED             REGION              ARCH
armv7l_4_8_3_std_1_latest   <bootscript>        84a15893            n/a                 []                  [arm]
x86_64_4_8_3_apparmor_1     <bootscript>        c2a7891b            n/a                 []                  [x86_64]
x86_64_4_8_3_std_1_latest   <bootscript>        4b9b80a5            n/a                 []                  [x86_64]
armv7l_4_4_26_std_1_stabl   <bootscript>        7d547f48            n/a                 []                  [arm]
x86_64_4_8_3_rancher_1      <bootscript>        d09eb9d6            n/a                 []                  [x86_64]
x86_64_4_8_3_fedora_1       <bootscript>        dafb7757            n/a                 []                  [x86_64]
x86_64_4_8_3_docker_1       <bootscript>        61648cb3            n/a                 []                  [x86_64]
x86_64_4_4_26_std_1_stabl   <bootscript>        20272fd0            n/a                 []                  [x86_64]
x86_64_4_4_21_std_1         <bootscript>        a31d40fd            n/a                 []                  [x86_64]
x86_64_4_8_3_debug_1        <bootscript>        1feffa10            n/a                 []                  [x86_64]
armv7l_4_8_3_docker_1       <bootscript>        e1ee48e3            n/a                 []                  [arm]
armv7l_4_8_3_apparmor_1     <bootscript>        5fef0f06            n/a                 []                  [arm]
armv7l_Rescue               <bootscript>        a5485ac0            n/a                 []                  [arm]
x86_64_rescue               <bootscript>        bf4cfb66            n/a                 []                  [x86_64]
armv7l_4_8_3_fedora_1       <bootscript>        bc2a2c2f            n/a                 []                  [arm]
```

**Comment by jesuscript** [comment]
awesome! I think that's all I need, thanks again

**Comment by zekiunal** [comment]
Hi; 

I am trying to run Docker Swarm Mode on Ubuntu Xenial (16.04 latest).

I am changing bootscript to x86_64 4.10.8 docker #1 and reboot then. 

this is docker installation script : 

```shell
sudo apt-get update -y
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common nfs-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce
sudo systemctl enable docker
```

```shell
PRIVATE_IP=$(/sbin/ifconfig eth0 | grep Mask | awk '{print $2}'| cut -f2 -d:);
sudo docker swarm init --advertise-addr ${PRIVATE_IP}
```

```shell
sudo docker service rm nginx
sudo docker service create --name nginx --publish 80:80 nginx
```

But nginx cannot reachable via browser. 

What's going on ? I could not move forward.

**Comment by VERGiL1202** [comment]
I am facing the same problem with the `x86_64 4.10.8 docker #1` bootscript.
Scaleway support just says "we do not make assistance on docker configuration".
Well, it's related to your custom kernel Scaleway! Guess I have to switch my cloud provider if there is no solution here.

**Comment by mbenedettini** [comment]
Rancher bootscripts seem to include it. I'm currently using `x86_64 4.10.8 rancher #1` and ports are being exposed just fine.

**Comment by insertjokehere** [comment]
This is still an issue - the latest `docker` bootscripts are missing `IP_VS_NFCT` which breaks swarm, and the `x86_64 4.10.8 rancher #1` bootscript mentioned previously doesn't seem to exist any more

**Comment by tbillon** [comment]
We've merged the different configurations into the `mainline` kernel. It should contain everything you need for docker.

**Comment by neolectron** [comment]
I still have this issue with your debian9 image.

**Comment by painslie** [comment]
@vadmeste I changed my Scaleway startup script to the latest `mainline` and it's working!!!

**Comment by lvnilesh** [comment]
I just built a Docker swarm using Debian Stretch and `x86_64 mainline 4.13` and I can not get swarm nodes to communicate with each other.
