### ISSUE TITLE
Fix the ubuntu 15.04 image with the new init system

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/image-ubuntu#8]
ubuntu 15.04 is currently broken (apt-get update && apt-get upgrade destroys the init), we have to port this image to systemd.

**Comment by moul** [comment]
https://github.com/scaleway/image-ubuntu/commit/74a4d1e9e007baa8a26fa38e3b68778df0e775e7

**Comment by moul** [comment]
Blocked by https://github.com/armbuild/docker-brew-ubuntu-debootstrap/issues/2

**Comment by aimxhaisse** [comment]
Tested 16 reboots with systemd and the new initrd, 16/16 OK.
