### ISSUE TITLE
DHCP lease is persistant after archive

### ISSUE THREAD

**Issue by bchatelard** [scaleway/image-ubuntu#83]
The dhclient is using leases files that are stored on the disk in `/var/lib/dhcp/dhclient.eth0.leases`.

In an archive sequence (stop, boot), the server will get stuck during the boot process if the node is located on another physical node (because the ip will change).

On a C2 the boot will stop right after:

```
...
[  OK  ] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Started Update UTMP about System Runlevel Changes.
```

The server will stop responding to ping at the exact same moment.
Since the lease is located on the disk, it is re-used during the boot by the dhclient, and give a wrong ip to eth0, the nbd connection will then stuck (on C2).

A temporary fix is to use the `INITRD_POST_SHELL=1` tag and connect to the serial then launch `rm /newroot/var/lib/dhcp/dhclient.eth0.leases` followed by ctrl-d to boot.

This issue might affect all distributions.

To address this issue we could:
- fix this directly in the initrd, by removing all the lease files (all possible locations are in the apparmor profile)
- create a new systemd job launched before `ifup@eth0.service` to cleanup leases at reboot.
- change the argument of dhclient line to work in `/tmp`
- ...

@moul @brmzkw @QuentinPerez what do you think ?

**Comment by moul** [comment]
The cleanest solution is to do it from a systemd service, so the user is still able to update the behavior if needed

A quick fix from the initrd ([in this file ?](https://github.com/scaleway/initrd/blob/master/Linux/tree-common/shutdown)) is smart enough, will work on the running images without requiring an update of the image and can still be disabled using some mechanism, i.e., adding an `if [ ! -f /var/lib/dhcp/no-initrd-cleanup]` check before actually deleting the file

**Comment by askz** [comment]
Hi, the fix doesn't work anymore. I have an instance that get stucks (I rebooted 10 times with deletion of the lease file) and I have no idea how to resolve this issue....
Any suggestions to bring back my production instance to life ?

**Comment by bchatelard** [comment]
Maybe you are impacted by another issue, can you open a ticket ?

**Comment by askz** [comment]
I opened one, your teammates invited me to wait for your support here.   
/!\ It's production instance, please don't try to reboot or whatever before asking me, I did dirty work Friday to get services running with chroot from initrd post shell.

Ticket Number : 0U5SR401

Thanks for your time.

**Comment by bchatelard** [comment]
Ok thanks, you might have been impacted by another issue, we can follow this in the ticket.

**Comment by askz** [comment]
Should I open another ticket in scaleway/image-debian since I had this bug in debian ?

**Comment by bchatelard** [comment]
Done in https://github.com/scaleway/initrd/commit/03a3f8949b5dbb2f8feeee6e8e7fe2ecaf41195d thanks @tbillon.

We released a new initrd with @moul fix, this issue should be fixed if you update to a recent bootscript.
