### ISSUE TITLE
bootscript for aarch64 points to kernel without modules and spurious "cloud-init=disabled" in kernel command line

### ISSUE THREAD

**Issue by rpardini** [scaleway/image-ubuntu#95]
Hi, support sent me here...
Hello! I've been trying out ARM64-8GB.
Very interesting virtual server, although I am completely blocked by the issues below.
Both refer to bootscript "aarch64 4.9.23 std #1 (stable/latest)" (which is the only available for these servers).
1) There are no Kernel Modules; this in turn prevents me from using iptables, which is essential; (http://mirror.scaleway.com/kernel/aarch64/4.9.23-std-1/modules/4.9.23-std-1/)
2) There is a gratuitous "cloud-init=disable" on the kernel cmdline, that blocks my own cloud-init provisioning from running.
Could you guys please fix that bootscript, or make a new one?
Thanks!

**Comment by rpardini** [comment]
Err... is there somewhere else I should ask for this? Thanks

**Comment by superseed** [comment]
Hey, this should be fixed now.

**Comment by rpardini** [comment]
Confirm kernel modules OK for PAR1, I'm testing new AMS1 servers right now. This makes it usable for me, fantastic little kvm machines.
Unfortunately, and I agree a different issue, is that "cloud-init=disable" is still present on the kernel cmdline, which forces me to hack into a systemd generator to enable the cloud-init services. I provision cloud-init myself, the image does not have cloud-init baked in.

**Comment by bchatelard** [comment]
HI, sorry about that, we just removed the `cloud-init=disable` it was not used.
Thanks for reporting this issue !

**Comment by rpardini** [comment]
Confirmed working on both AMS1 and PAR1. Thanks.
