### ISSUE TITLE
Docker installs on Zetsy, but won't run

### ISSUE THREAD

**Issue by italomaia** [scaleway/image-ubuntu#98]
As the title says: docker will install on ARM zetsy without problem, but, if you try to download and run an image, it will break with the following error:

standard_init_linux.go:187: exec user process caused "exec format error"

Ideas?

**Comment by italomaia** [comment]
This might be related:
https://github.com/moby/moby/issues/26495

**Comment by bchatelard** [comment]
How are you installing docker ?
This error is usually when you are trying to execute an x86_64 binary on arm.

A Docker image is available for C1 if you want.

**Comment by italomaia** [comment]
I saw it needs special container images to run. ARM containers. With them, it runs. Won't work with docker-machine, although. No matter the setup. I have no idea why. 
C1 docker image uses a quite outdated docker version. Right now, I gave up on the ARM container until I have a specific, non docker need for it. The X86 container is doing fine so far.
